### ISSUE TITLE
Buckle up for V2

### ISSUE THREAD

**Issue by vikiival** [kodadot/rubick#152]
> the best place to check I would say:

1. https://www.crowdcast.io/e/buidl
2. https://github.com/rmrk-team/rmrk2-examples
3. https://github.com/rmrk-team/rmrk-spec/tree/master/standards/kusama

(resources to study from the best RMKR dev)
<img src="https://user-images.githubusercontent.com/22471030/194898938-ddfb05d1-68fe-4f4b-98c2-13c7e0653634.jpeg" width="300" height="300" />

## (TODO):

- [x] move current impl into `mappings/v1` dir
- [x] add new V2 imple into `mappings/v2` dir
- [x] `mappings/index.ts` should decide whether to call `mainFrame` or `mainFrameAsV2`
- [x] for both impls split interaction into separated handles

Done until 64709af4f34262064d3d275a1525def32d1760b4

## Implentation:

The following **entities** are defined:

- [ ] [Collection + Metadata]
- [ ] [NFT + Metadata]
- [ ] [BASE] - template resource with themes and parts from which to build an
      NFT's render

The following **interactions** are possible:

- [ ] [ACCEPT] (Accept the addition of a new resource to an existing NFT, or
      the addition of a child into a parent NFT)
- [ ] [BASE] (Create a [Base])
- [ ] [BUY] (Buy an NFT)
- [ ] [CHANGEISSUER] (Changing the issuer of a collection or base)
- [ ] [BURN] (Burn an NFT)
- [ ] [CREATE] (Minting a collection of NFTs)
- [ ] [EMOTE] (Send a reaction/emoticon)
- [ ] [EQUIP] (Equip a child NFT into a parent's slot, or unequip)
- [ ] [EQUIPPABLE] (Changes the list of equippable collections on a
      base's part)
- [ ] [LIST] (List an NFT for sale)
- [ ] [LOCK] (Locking a collection)
- [ ] [MINT] (Minting an NFT inside a collection)
- [ ] [RESADD] (Add a new resource to an NFT as the collection issuer)
- [ ] [SEND] (Sending an NFT to a recipient)
- [ ] [SETPROPERTY] (Set a custom value on an NFT)
- [ ] [SETPRIORITY] (Set a different order of resource priority)
- [ ] [THEMEADD] (Add a new theme to a base)

**Comment by yangwao** [comment]
009?
